# docker-compose.yml

#version: '3.8'


services:
  cai-db:
    image: postgres:13
    container_name: cai-db
    restart: always
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
      POSTGRES_DB: shortener
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data between restarts
    networks:
      app: null
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "shortener"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: django_backend
    environment:
      - POSTGRES_USER = shortener
      - POSTGRES_PASSWORD = shortener
      - POSTGRES_NAME =  shortener
      - POSTGRES_HOST =  cai-db
      - DEBUG = True
    ports:
      - "8000:8000"
    networks:
      app: null
    depends_on:
      - cai-db
    links:
      - cai-db
    env_file:
      - ./server/.env
    restart: on-failure

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    networks:
      app: null
    environment:
      - REACT_APP_API_URL=http://center.ai:8000/api
      - REACT_DJANGO_USER=andrzej
      - REACT_DJANGO_PASSWORD=admin123
    depends_on:
      - backend


networks:
  app:
    driver: bridge
#    external: true

volumes:
  postgres_data:
    driver: local


