# docker-compose.yml

#version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: django_backend
    environment:
      - SHORT_LINK_LENGTH=8
      - DEFAULT_COUNTRY = Poland
      - DOMAIN_NAME = http://center.ai/
      - SHORT_LINK_LENGTH = 8
      - DB_USER = andrzej
      - DB_PASSWORD = shortener
      - DB_NAME =  shortener
      - DEBUG = True
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
#    env_file:
#      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://center.ai:8000/api/
      - REACT_DJANGO_USER=andrzej
      - REACT_DJANGO_PASSWORD=ad
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: genius
      POSTGRES_PASSWORD: nation
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
